require "simon.options"
require "simon.keymaps"
require "simon.plugins"
require "simon.colorscheme"
-- require "simon.alpha"
require "simon.dashboard"
require "simon.autopairs"
require "simon.lualine"
require "simon.telescope"
require "simon.comment"
require "simon.transparent"
require "simon.bufferline"
require "simon.nvim-tree"
require "simon.colorizer"
require "simon.neoscroll"
