# alias
alias 'vim'='nvim'
alias 'v'='nvim'
alias 'lg'='lazygit'
alias 'yz'='yazi'
alias 'y'='yazi'
alias 'ez'='exec zsh'
alias 'gp'='git pull'
alias 'gs'='git status'
alias 'gc'='git commit'
alias 'ga'='git add'
alias 'gl'='git log'
alias 't'='tmux'
alias 'tl'='tmux list'
alias 'ta'='tmux attach'
alias 'tk'='tmux kill-ses'
alias 'neo'='neofetch'
